-- Categories tablosunu oluştur
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.categories(id),
  name text not null,
  slug text not null unique,
  icon text,
  icon_color text,
  level integer default 0,
  extra_fields_config jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (Row Level Security) aç
alter table public.categories enable row level security;

-- Herkes okuyabilir (Select)
create policy "Categories and subcategories are viewable by everyone"
  on public.categories for select
  using ( true );

-- Sadece Adminler ekleyebilir/düzenleyebilir/silebilir
-- Bu policy, 'profiles' tablosunda 'is_admin' alanının kontrolüne dayanır.
create policy "Admins can insert categories"
  on public.categories for insert
  with check (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.is_admin = true
    )
  );

create policy "Admins can update categories"
  on public.categories for update
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.is_admin = true
    )
  );

create policy "Admins can delete categories"
  on public.categories for delete
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.is_admin = true
    )
  );
